[project]
name = "llada-minimal-quickstart"
version = "0.1.0"
description = "LLaDA minimal quickstart fork."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"torch>=2.6.0",
	"transformers>=4.0"
]
